DataBaseEntities/Controllers/CityController.cs
using DataBaseEntities.Data;
using DataBaseEntities.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DataBaseEntities.Controllers
{
    public class CityController : Controller
    {
      
        public readonly ApplicationDbContext _context;

        public CityController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        public IActionResult Index()
        {

            return View(_context.Cities.Select(a=>new CityReadViewModel() {name = a.CityName }).ToList());
        }

        //Action for Adding City (Only Admin can add a city)
        [Authorize(Roles = "Admin")]
        public IActionResult AddCity()
        {
            ViewBag.Countries = _context.Countries.ToList();
            return View();
        }

        //Sending user input for adding city
        [HttpPost]
        public IActionResult AddCity(CityCreationViewModel userInput)
        {
            if (ModelState.IsValid)
            {
                Country selectedCountry = _context.Countries.FirstOrDefault(a => a.CountryName == userInput.CountryName);
                

                City newCity = new City {CityName = userInput.CityName , Country = selectedCountry };
                _context.Cities.Add(newCity);
                selectedCountry.Cities.Add(newCity);
                _context.Countries.Update(selectedCountry);
                _context.SaveChanges();
            }

        
            return RedirectToAction("Index");
        }

        //Action for deleting a city(Only Admin can delete a city)
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteCity(string cityName)
        {
            var cityToDelete = _context.Cities.FirstOrDefault(x => x.CityName == cityName);
            _context.Cities.Remove(cityToDelete);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

DataBaseEntities/Controllers/CountryController.cs
using DataBaseEntities.Data;
using DataBaseEntities.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DataBaseEntities.Controllers
{
    public class CountryController : Controller
    {
        public readonly ApplicationDbContext _context;

        public CountryController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View(_context.Countries.Select(a=>new CountryViewModel { Name= a.CountryName}).ToList());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AddCountry()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCountry(CountryViewModel country)
        {
            if (ModelState.IsValid)
            {
                _context.Countries.Add(new Country() { CountryName = country.Name });
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet("country/cities/{countryName}")]
        public IActionResult GetCitisByCountryName([FromRoute] string countryName) {
            Country chosenCountry = _context.Countries.Where(a => a.CountryName == countryName).Include(b=>b.Cities).FirstOrDefault();
            if (chosenCountry == null) return NoContent(); //status : 202
            IEnumerable<string> cityNames = chosenCountry.Cities.Select(a => a.CityName);
            return Ok(cityNames);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteCountry(string countryName)
        {
            var countryToDelete = _context.Countries.FirstOrDefault(x => x.CountryName == countryName);
            _context.Countries.Remove(countryToDelete);
            _context.SaveChanges();

                return RedirectToAction("Index");
        }


    }
}

DataBaseEntities/Controllers/LanguageController.cs
using DataBaseEntities.Data;
using DataBaseEntities.Models;
using DataBaseEntities.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DataBaseEntities.Controllers
{
    public class LanguageController : Controller
    {
        public readonly ApplicationDbContext _context;

        public LanguageController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View(_context.Languages.Select(a=>new LanguageViewModel() { Name = a.LanguageName}).ToList());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult AddLanguages()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddLanguages(LanguageViewModel language)
        {
            if (ModelState.IsValid)
            {
                _context.Languages.Add(new Language() { LanguageName = language.Name});
                _context.SaveChanges();
            }


            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteLanguage(string languageName)
        {
            var languageToDelete = _context.Languages.FirstOrDefault(x => x.LanguageName == languageName);
            _context.Languages.Remove(languageToDelete);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

DataBaseEntities/Controllers/PersonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataBaseEntities.Data;
using DataBaseEntities.Models;
using DataBaseEntities.Models.ViewModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace DataBaseEntities.Controllers
{
    public class PersonController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PersonController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
       
        public IActionResult ListPeople()
        {
            var cityLanguageCountry = _context.People
                .Include(a => a.City)
                .Include(k => k.Country)
                .Include(a=>a.LanguagePerson)
                .ToList();
 
            return View(cityLanguageCountry);

        }
        
        public IActionResult AddPerson()
        {
            ViewBag.Cities = _context.Cities.ToList();
            ViewBag.Languages = _context.Languages.ToList();
            ViewBag.Countries = _context.Countries.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult AddPerson(PersonCreationViewModel person)
        {
            if (ModelState.IsValid)
            {
                City city = _context.Cities.Where(a => a.CityName == person.CityName).Include(a=>a.People).FirstOrDefault();
               
                IEnumerable<Language> languages = _context.Languages.Where(b => person.LanguageName.Contains(b.LanguageName));
                Country country = _context.Countries.FirstOrDefault(k => k.CountryName == person.CountryName);
                


                Person p = new Person
                {
                    Name = person.FullName,
                    PhoneNumber = person.PhoneNum,
                    City = city,
                    Country = country
                };

                _context.People.Add(p);
                _context.SaveChanges();

                Person insertedPerson = _context.People.FirstOrDefault(a => a.Name == p.Name);
                
                List<LanguagePerson> languagePerson = new List<LanguagePerson>();
                foreach(var l in languages)
                {
                    languagePerson.Add(new LanguagePerson()
                    {
                        Language = l,
                        Person = insertedPerson
                    });
                }
                _context.LanguagePerson.AddRange(languagePerson);
                city.People.Add(p);

                _context.Cities.Update(city);
                _context.SaveChanges();
            }

            return RedirectToAction("ListPeople");
        }

       
        public IActionResult DeletePerson(int id)
        {

            var personToDelete = _context.People.Find(id);
            _context.People.Remove(personToDelete);
            _context.SaveChanges();

            return RedirectToAction("ListPeople");
        }
    }
}

DataBaseEntities/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Entity Framework Project </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container"><br>
               
                                   <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                                       <partial name="_LoginPartial" />
                                       <ul class="navbar-nav flex-grow-1">
                                           <li class="nav-item">
                                               <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                           </li>

                                           <li class="nav-item">
                                               <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="ListPeople">List of People</a>
                                           </li>
                                               @if (User.Identity.IsAuthenticated)
                                               {
                                                   <li class="nav-item">
                                                       <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">List of Cities</a>
                                                   </li>
                                                   <li class="nav-item">
                                                       <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">List of Countries</a>
                                                   </li>

                                                   <li class="nav-item">
                                                       <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Index">List of Languages</a>
                                                   </li>
                                               }


                                       </ul>
                                   </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Maryam Rezaee - Entity FramWork Project - 2022
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>